baseURL: /acme
languageCode: es-es
title: Acme
theme: basico

author: 
  facebook: "https://facebook.com/example" 
  twitter: "https://twitter.com/example" 
  email: "contact@example.org" 
  name: "Acme Corporation" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 

menu:
  main: 
    - identifier: viajes 
      name: viajes 
      url: /viajes
      pageRef: viajes
      weight: 10 
    - identifier: curriculum 
      name: Curriculum 
      url: /curriculum 
      pageRef: curriculum
      weight: 50 
    - identifier: acerca de 
      name: Acerca de 
      url: /about 
      pageRef: about
      weight: 100  
    - identifier: blog
      name: blog
      url: /blog
      pageRef: blog
      weight: 70
    - identifier: contacto
      name: contacto 
      url: /contacto 
      pageRef: contacto
      weight: 200 
    - identifier: tv 
      name: canales 
      url: /television/canales
      pageRef: tv
      weight: 250
    - identifier: pelis 
      name: peliculas 
      url: /peliculas/pelis
      pageRef: pelis
      weight: 300
    - identifier: institutos 
      name: centros 
      url: /centros/institutos
      pageRef: institutos
      weight: 350
params: 
  colorPickerEnabled: true
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.      


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true